let completequestions = [
["What's a favorite recent memory?", "experience", false,"phillip", true,"",4],
["What do you love most about your favorite community?", "people", false,"phillip", true,"",6],
["What are you most passionate about?", "worldview", false,"phillip", false,"",6],
["If you had one day left to live, what would you do?", "fantasy", false,"phillip", false,"",4],
["What is the biggest lesson you've learned in life?", "worldview", false,"phillip", false,"",6],
["What are you most proud of yourself for?", "worldview", false,"phillip", false,"",6],
["Who do you look up to?", "people", false,"phillip", false,"",4],
["Was it worth it?", "experience", true,"coderystal", true,"",4],
["What qualities do you love the most about your role model(s)?", "people", false,"phillip", false,"",4],
["If money was not an issue, what would you do?", "fantasy", false,"phillip", false,"",4],
["Where do you hope to see yourself in 5 years?", "goals", false,"phillip", true,"",4],
["Have you ever had your heart broken?", "experience", false,"phillip", true,"",5],
["What is the most unforgettable moment in your life so far?", "experience", false,"phillip", false,"",5],
["What's your favorite quote that you live by?", "worldview", false,"phillip", true,"",2],
["What makes you happy?", "likes", false,"phillip", false,"",2],
["What do you love about your life?", "likes", false,"phillip", false,"",6],
["What do you consider as your greatest strengths and weaknesses?", "worldview", false,"phillip", false,"",6],
["What are you most grateful for?", "likes", false,"phillip, toastmasters", false,"",6],
["What is one thing you want to change in this world?", "dislikes", false,"phillip", false,"",6],
["What is one thing you're trying to change about yourself?", "goals", false,"phillip", true,"",6],
["What is something you always wanted to say?", "worldview", false,"phillip", true,"",4],
["Who matters the most to you?", "people", true,"phillip", false,"",6],
["What worries you the most?", "dislikes", false,"phillip", false,"",6],
["If you could have one wish granted, what would it be?", "fantasy", false,"phillip", true,"",2],
["What is something you always wanted to learn/do but life just got in the way?", "fantasy", false,"phillip", false,"",4],
["What is something you wish you had more time to do?", "fantasy", false,"phillip", false,"",4],
["Who do you need to get in touch with because it's been too long?", "people", false,"phillip", false,"",4],
["What is something new you recently tried and enjoyed?", "experience", false,"phillip", false,"",4],
["What will you have wanted to accomplish by the time you're 100?", "goals", false,"phillip", false,"",4],
["Describe something you achieved that you didn't think was possible.", "experience", false,"phillip", false,"",4],
["What gives you hope?", "worldview", false,"phillip", false,"",6],
["What is a new habit you want to pick up?", "goals", false,"phillip", false,"",4],
["What life advice would you offer a newborn infant (given that they will remember it)?", "worldview", false,"phillip", false,"",6],
["When did you last cry? Why, and who was with you?", "experience", false,"phillip", true,"",4],
["What matters to you?", "worldview", true,"phillip", true,"",6],
["What is your greatest accomplishment?", "experience", false,"phillip", false,"",4],
["What is something you do differently than most people?", "tendencies", false,"phillip", false,"",2],
["What is your next great adventure?", "goals", false,"phillip", false,"",4],
["What's one thing that could happen today that would make it great?", "likes", false,"phillip", false,"",1],
["What/Who inspires you?", "people", false,"phillip", false,"",4],
["What are the little things you stop to appreciate and enjoy?", "likes", false,"phillip", false,"",1],
["What does home mean to you?", "worldview", false,"phillip", false,"",3],
["What are some things you don't want to die before doing?", "goals", false,"phillip", true,"",4],
["How do you show your love?", "people", false,"phillip", false,"",3],
["What needs to happen?", "worldview", true,"coderystal", true,"",5],
["What scar that you have has the best story?", "experience", false,"phillip", false,"",3],
["Where do you feel most free? Where do you feel most free to express yourself?", "likes", false,"phillip", false,"",6],
["What do you stand for?", "likes", true,"phillip", false,"",6],
["What are you most committed to?", "goals", false,"phillip", false,"",6],
["What advice would you give yourself 5 years ago?", "worldview", false,"phillip", false,"",4],
["Describe a turning point in your life.", "experience", false,"phillip", false,"",5],
["If you only have one hour left to live, who would you be with?", "people", false,"phillip", false,"",4],
["What is the kindest/sweetest thing someone has ever done for you?", "experience", false,"phillip", false,"",4],
["What/Who do you miss the most?", "experience", false,"phillip", false,"",4],
["Describe your perfect day.", "fantasy", false,"phillip, toastmasters", true,"",3],
["What do you value most in a friend/relation -ship?", "people", false,"phillip", false,"",4],
["What does love mean to you?", "people", false,"phillip", false,"",4],
["Is love real? Is it worth it?", "people", true,"phillip", true,"",2],
["Tell us about your mother and your relationship with her.", "people", false,"phillip", false,"",6],
["Tell us about your father and your relationship with him.", "people", false,"phillip", false,"",6],
["Which parent are you closer to?", "people", false,"phillip", false,"",3],
["What was your biggest failure and how did you overcome it?", "experience", false,"phillip", false,"",5],
["What's your greatest achievement and how did it shape you?", "experience", false,"phillip", false,"",5],
["In what ways do you hold yourself back?", "tendencies", false,"phillip", false,"",6],
["What was your dream job growing up?", "fantasy", false,"phillip", false,"",2],
["If you could change one thing about yourself, what would it be?", "dislikes", false,"phillip", false,"",4],
["What makes you cry?", "dislikes", false,"phillip", false,"",4],
["What's your fondest childhood memory?", "experience", false,"phillip, toastmasters", true,"",3],
["What has been the best phase in your life?", "experience", false,"phillip", false,"",3],
["What has been the worst phase in your life?", "experience", false,"phillip", false,"",5],
["What is a relationship dealbreaker for you?", "people", false,"phillip", false,"",4],
["When do you think a person is ready for marriage?", "worldview", false,"phillip", false,"",2],
["What's on your bucket list this year?", "goals", false,"phillip", false,"",3],
["What did your past relationship teach you?", "people", false,"phillip", false,"",5],
["Share a moment when you were thankful that you stepped outside of your comfort zone.", "experience", false,"phillip", true,"",3],
["Share a moment that ignited or re-ignited your passion.", "experience", false,"phillip", true,"",5],
["What's your proof?", "experience", true,"coderystal", true,"",4],
["Who are you thankful to have met or reconnected with recently?", "people", false,"phillip", false,"",4],
["Think of a person you met recently that improved your experience, what would you like to say to them?", "people", false,"phillip", false,"",4],
["What is your most unforgettably magical moment?", "experience", false,"phillip", true,"",4],
["If you walked into a room with everyone you have ever met, who would you go looking for first?", "people", false,"phillip", false,"",5],
["Tell us about how something that happened recently will continue to affect your life.", "experience", false,"phillip", true,"",5],
["When did you not speak up when you should have?", "worldview", false,"phillip, toastmasters", false,"",5],
["Think of the last time you were really angry. How do you feel about it now?", "experience", false,"phillip", true,"",5],
["Have you ever failed somebody?", "people", false,"phillip", true,"",5],
["Have you ever had to give up on something or someone for the sake of another?", "people", false,"phillip", false,"",5],
["What drives you to do better at something?", "tendencies", false,"phillip", false,"",4],
["What is one thing you wish you could do?", "fantasy", false,"phillip", true,"",3],
["What worries you most about the future?", "dislikes", false,"phillip", false,"",6],
["What are you holding onto that you need to let go of?", "tendencies", false,"phillip", false,"",6],
["Why do you matter?", "worldview", false,"phillip, toastmasters", false,"",6],
["Are you happy?", "goals", true,"coderystal", true,"",6],
["What is one fear that you know is holding you back?", "tendencies", false,"phillip", false,"",6],
["Why are you here? Why are we here?", "worldview", true,"phillip", true,"",6],
["What have you done that you are not proud of?", "experience", false,"phillip, toastmasters", false,"",5],
["In what way are you your own worst enemy?", "tendencies", false,"phillip, toastmasters", false,"",6],
["What has been draining your happiness?", "dislikes", false,"phillip", false,"",6],
["What is the #1 thing you intend to accomplish before you die?", "goals", false,"phillip, toastmasters", false,"",6],
["What are you looking to be remembered for? Why is this important to you?", "goals", false,"phillip", true,"",6],
["If there is one person that you could talk to, dead or alive, who would it be?", "fantasy", false,"phillip", false,"",2],
["What's the most difficult decision you have had to make?", "experience", false,"phillip", false,"",5],
["How would you describe your childhood?", "experience", false,"phillip", false,"",5],
["What dreams do you have for your children? How similar are they to your parents' dream for you?", "worldview", false,"phillip", true,"",6],
["Where am I wrong?", "worldview", false,"phillip", false,"",4],
["How would you characterize your thoughts? Are they generally hurting or healing?", "tendencies", false,"phillip", true,"",6],
["Truly, is your current career path what you really want to be doing?", "goals", false,"phillip", true,"",6],
["How do you expect to be remembered, if you were to die today?", "identity", false,"phillip", true,"",3],
["What is your biggest fear?", "dislikes", false,"phillip", false,"",6],
["Who is someone you need to forgive?", "people", false,"phillip", false,"",4],
["How do you define who you are?", "worldview", false,"phillip", false,"",6],
["What do you really want?", "likes", true,"phillip", false,"",6],
["What is something you need to get off your chest?", "experience", false,"phillip", true,"",4],
["What are your triggers and what causes them?", "dislikes", false,"phillip", false,"",7],
["Is there anyone you hold a grudge against? If so, what's holding you back from letting go and moving on?", "people", false,"phillip", false,"",7],
["Do you feel misunderstood? If so, what are common misconceptions about you?", "people", false,"phillip", true,"",6],
["What's the worst thing you have done in your life and why did you do it?", "experience", false,"phillip", false,"",7],
["Do you lie to yourself to avoid addressing your fears?", "tendencies", false,"phillip", false,"",6],
["When are you hardest on yourself?", "dislikes", false,"phillip", false,"",6],
["Do you enforce boundaries on others or do you let people cross lines?", "people", false,"phillip", false,"",7],
["Are you 100% when you're around other people? Do you put on a mask or persona?", "people", false,"phillip", true,"",4],
["Do you know who you are?", "identity", false,"phillip", true,"",6],
["Do you forgive yourself when you make a mistake? When you make mistakes can you move on from them or do they continue to hurt you?", "tendencies", false,"phillip", false,"",6],
["What are your toxic traits?", "tendencies", false,"phillip", false,"",4],
["Are you happy being alone with your own company?", "people", false,"phillip", true,"",6],
["How do you respond to criticism and feedback? What are you sensitive about?", "tendencies", false,"phillip", true,"",6],
["Do you allow yourself to be vulnerable? Do you put walls up or allow yourself to be open?", "tendencies", false,"phillip", false,"",6],
["Do you accept yourself as you are?", "tendencies", false,"phillip", false,"",6],
["Do you feel as though people respect you?", "people", false,"phillip", false,"",6],
["Do you have any unhealthy attachment or habits? Do you try to curb them or entertain them?", "tendencies", false,"phillip", false,"",5],
["Which emotion makes you feel the most uncomfortable? Which emotion do you try to avoid?", "tendencies", false,"phillip", false,"",4],
["Which negative emotion are you most comfortable with? Do you cling onto a certain emotion on a daily basis to feel normal?", "tendencies", false,"phillip", true,"",6],
["Is your inner voice kind or critical? What does it say to you on a normal day?", "tendencies", false,"phillip", false,"",6],
["Is your inner voice truly yours? Whose voice could be influencing your inner voice? (parents, peers, etc.)", "tendencies", false,"phillip", true,"",6],
["Do you downplay what you really feel or have been feeling for the sake of others?", "people", false,"phillip", true,"",6],
["Why do you let people who don't acknowledge your feelings stay in your life? Do you have a desire to keep their company? Or do you know that there's a way to make the relationship better?", "people", false,"phillip", false,"",7],
["Do you value yourself and what you bring to the table?", "identity", false,"phillip", false,"",6],
["How can you be more kind to yourself? How do you sabotage yourself?", "tendencies", false,"phillip", false,"",6],
["How important are you to yourself?", "identity", false,"phillip", false,"",6],
["Have you ever made someone else feel proud of you? If so, who?", "people", false,"phillip", true,"",4],
["When you accomplish something, how satisfied are you, and for how long?", "identity", false,"phillip", true,"",4],
["What are your most undesirable traits and characteristics? How can you work on them?", "tendencies", false,"phillip", false,"",4],
["What image do you think people have of you versus how would you like others to describe you? What are the differences between the two images and which one do you like better?", "people", false,"phillip", false,"",4],
["What is your definition of failure and success?", "identity", false,"phillip", false,"",2],
["What is your definition of perfect, and is it attainable?", "worldview", false,"phillip", false,"",2],
["Do you hold yourself to a higher standard than other people?", "tendencies", false,"phillip", false,"",4],
["In what ways do you feel inferior to others?", "people", false,"phillip", false,"",4],
["Have you ever sacrificed a part of yourself to fit in better? How do you feel about it now?", "identity", false,"phillip", false,"",4],
["Have you ever felt abandoned by others around you? In what ways have you abandoned others?", "people", false,"phillip", false,"",5],
["In what ways do you not show up for yourself that you do for others?", "people", false,"phillip", true,"",4],
["What do you still need to forgive yourself for?", "identity", false,"phillip", false,"",6],
["What do you feel most guilty for?", "identity", false,"phillip", false,"",6],
["Have you ever stayed in a relationship that you knew deep down was not good for you? (romantic, work, friends) Why did you stay?", "people", false,"phillip", true,"",5],
["Do you feel worthy of the good things in your life?", "worldview", false,"phillip", false,"",6],
["Describe the time you felt most alone.", "experience", false,"phillip", false,"",7],
["How do you let people take advantage of you? Does acknowledging that people have taken advantage of you bring up certain emotions? What would you do differently?", "people", false,"phillip", true,"",6],
["Where do you need to set better boundaries in your life?", "tendencies", false,"phillip", false,"",4],
["Did you get the support and respect you needed in your childhood from parents, teachers, and peers? How did that shape you into the person you are today?", "people", false,"phillip", false,"",5],
["If you had to take a negative experience and reframe it positively, how would you do it? How does the act of reframing make you feel?", "experience", false,"phillip", false,"",6],
["In what ways do you seek validation from others?", "people", false,"phillip", false,"",6],
["What is the biggest lie you keep telling yourself? Where did it come from?", "tendencies", false,"phillip", false,"",6],
["Tell us about a time you were let down by someone you looked up to.", "people", false,"phillip", true,"",5],
["What's a trait you see in other people that you wish you had? Why do you not have that trait yourself?", "likes", false,"phillip", false,"",4],
["Do you find yourself over-thinking about what you say or how you acted? What usually triggers this?", "tendencies", false,"phillip", false,"",4],
["What tends to trigger envy for you?", "tendencies", false,"phillip", true,"",4],
["What frustrates you about your parents and siblings? Do you have similar traits?", "people", false,"phillip", false,"",4],
["Which emotions are you afraid of showing others?", "people", false,"phillip", false,"",6],
["How can you give others more space and acceptance to be themselves around you?", "people", false,"phillip", false,"",4],
["What do you keep getting accused of? When was the first time?", "tendencies", true,"phillip", true,"",6],
["What are some beliefs you tend to expect others to agree with you on? In general, and in specific communities?", "worldview", false,"phillip", true,"",6],
["What were you brought up to value in your family? How are your own values similar or different?", "worldview", false,"phillip", false,"",4],
["What family patterns do you fear repeating?", "worldview", false,"phillip", false,"",7],
["In what situations do you feel less than others, equal to others, and better than others? Why do you feel this way?", "people", false,"phillip", false,"",6],
["Tell us about a time you opened up to someone and felt rejected? A time you felt accepted?", "people", false,"phillip", false,"",5],
["When were you last jealous of someone? What did you want to have?", "likes", false,"phillip", true,"",5],
["What behaviors in others upset you the most?", "dislikes", false,"phillip", true,"",4],
["Which dreams of yours feel possible? Which feel impossible?", "goals", false,"phillip", true,"",4],
["Which past version of yourself do you hope no one ever sees?", "dislikes", false,"phillip", false,"",6],
["What event has hurt you the most in your life? What reminds you of that time? What parts of you still remain there?", "experience", false,"phillip", false,"",7],
["What is a negative thing you can not stop telling yourself?", "dislikes", false,"phillip", false,"",7],
["What lies are you telling yourself right now?", "tendencies", false,"phillip", false,"",6],
["What made you feel unloved as a child?", "people", false,"phillip", true,"",5],
["What was the main thing you wanted in your childhood that you never received? How do you think that shaped you?", "likes", false,"phillip", true,"",5],
["Do you allow yourself to be sad? Do you allow yourself to be angry?", "tendencies", false,"phillip", false,"",4],
["What is the worst thing you have done to yourself? Why did you do it? How can you make it up to yourself and show yourself love?", "identity", false,"phillip", false,"",7],
["Do you blame your parents for anything? Now that you are older, do you feel like you understand their actions more?", "people", false,"phillip", false,"",6],
["Is it easy for you to ask for help? Does it make you feel weak and vulnerable?", "people", false,"phillip", true,"",4],
["What can you not accept about yourself?", "tendencies", false,"phillip", false,"",4],
["Do you have any secrets you intend to take to your grave?", "identity", false,"phillip", true,"",5],
["Who have you been pretending to be?", "tendencies", true,"phillip", false,"",6],
["Are you resisting your here and now?", "people", false,"phillip", false,"",6],
["What harm are you trying to protect yourself from?", "tendencies", false,"phillip", false,"",6],
["What or who are you passionate enough about to endure anything for?", "likes", false,"phillip", false,"",6],
["What gets in the way of your authenticity?", "tendencies", false,"phillip", false,"",6],
["In what ways are you playing a victim in your life? How can you play a hero in your life?", "tendencies", false,"phillip", false,"",6],
["What qualities did you initially admire about your ex? In what ways have you developed this quality in yourself before the relationship?", "people", false,"phillip", true,"",4],
["Nobody enjoys feeling hurt, rejected, heartbroken, jealousy, etc. what is the very worst feeling for you personally? Where does that come from?", "dislikes", false,"phillip", false,"",6],
["Do you have healthy boundaries? What is allowing or preventing you from having the courage to hold that space?", "tendencies", false,"phillip", false,"",5],
["What makes you feel empty? How do you tend to fill that void?", "tendencies", false,"phillip", false,"",6],
["Who has the most influence over you? Is that healthy?", "people", false,"phillip", false,"",5],
["Is there anything you would want to say now to someone who once significantly hurt you?", "people", false,"phillip", true,"",7],
["What memories bring you shame? What led to your behavior?", "identity", false,"phillip", true,"",6],
["With whom or in what situations do you find yourself putting on a mask or a different persona? What do you think will happen if you expose your true self?", "identity", false,"phillip", false,"",6],
["What are your negative traits and how do you think they developed? Do you think they were useful for you in the past?", "tendencies", false,"phillip", true,"",6],
["Which relationships in your life no longer serve you? How would you feel if you allowed these relationships to dissolve? Is it worth salvaging?", "people", false,"phillip", true,"",6],
["How are you letting yourself down at this moment in life?", "dislikes", false,"phillip", false,"",6],
["Who do you owe an apology to? What would you say to them now?", "people", false,"phillip", false,"",4],
["Who owes you an apology? What would you say to them now?", "people", false,"phillip", false,"",5],
["What situation in your life do you most wish had a different outcome?", "experience", false,"phillip", false,"",5],
["What is the worst emotion someone can provoke from you? Why do you feel so strongly about this?", "dislikes", false,"phillip", false,"",6],
["How can you let go?", "tendencies", true,"phillip", false,"",6],
["What do you miss the most about your ex and your life with them? What did you learn about that relationship?", "people", false,"phillip", false,"",5],
["Who disappointed you as a child? Do you have any similarities with them?", "people", false,"phillip", false,"",4],
["How often do you forgive yourself? What do you feel you need to be forgiven for?", "tendencies", false,"phillip", false,"",6],
["How do you carry the weight of your past trauma? How does it manifest in your life now?", "experience", false,"phillip", false,"",7],
["How did you deal with trauma in the past and how do you combat it in the present?", "tendencies", false,"phillip", false,"",7],
["How do you enforce boundaries? How do you feel when people overstep them?", "tendencies", false,"phillip", false,"",6],
["What is the biggest promise to you that someone else has broken? How did that make you feel?", "people", false,"phillip", false,"",7],
["What is the biggest promise you have broken? Why did you break it? How did it make you feel?", "people", false,"phillip", false,"",6],
["Are you being fully honest with yourself right now?", "identity", false,"phillip", false,"",6],
["Are you holding onto people that don't deserve you?", "people", false,"phillip", false,"",6],
["Do you feel unloved or unworthy as an adult?", "identity", false,"phillip", false,"",6],
["What steps can you take to give more self love and self-worth to yourself?", "identity", false,"phillip", false,"",6],
["Why did you do it?", "identity", true,"phillip", false,"",4],
["Do you use other people to fill a void?", "people", false,"phillip", true,"",6],
["How do you handle disappointment?", "tendencies", false,"phillip", false,"",4],
["What pain or emotions are you trying to escape from?", "tendencies", false,"phillip", false,"",7],
["If you met yourself for the first time, what would your first impression be?", "tendencies", false,"phillip", false,"",3],
["If you were to write an apology letter to yourself, what would you say?", "identity", false,"phillip", false,"",6],
["Are you safe?", "identity", true,"phillip", true,"",7],
["In what ways are you privileged? What do you take for granted?", "tendencies", false,"phillip", true,"",5],
["What is something that you always complain about? What ownership do you have in that situation?", "dislikes", false,"phillip", false,"",4],
["What personal vices do you wish you had more control over?", "tendencies", false,"phillip", false,"",7],
["What need do your vices satisfy? (Distraction, feeling loved? Calms anxiety, etc.)", "tendencies", false,"phillip", true,"",6],
["In what ways are you like your guardians? In what ways do you hope you are not like them?", "people", false,"phillip", false,"",6],
["What family patterns do you fear you are repeating?", "tendencies", false,"phillip", false,"",7],
["How would you describe your life to your child? What parts should you emphasize? What parts would you leave out?", "experience", false,"phillip", false,"",5],
["What relationship pattern has followed you throughout your life? What would happen if you broke this pattern?", "people", false,"phillip", true,"",7],
["How worthy do you honestly believe you are?", "identity", false,"phillip", false,"",6],
["Do you stay silent so as to not experience rejection? Where do you think this started?", "tendencies", false,"phillip", false,"",6],
["Who or what have you taken for granted?", "people", false,"phillip", false,"",6],
["Which behavior do you judge most in yourself? Is your judgment justified?", "dislikes", false,"phillip", false,"",6],
["Why not?", "tendencies", true,"coderystal", true,"",4],
["Which behavior do you judge most in others? Is your judgment justified?", "dislikes", false,"phillip", false,"",6],
["If you could get rid of one memory, which would it be? Why, and how would it affect who you are right now?", "dislikes", false,"phillip", true,"",7],
["Which of your memories is the most painful to you?", "experience", false,"phillip", false,"",7],
["Are you truly good at asking for help? What is really holding you back?", "tendencies", false,"phillip", false,"",6],
["What qualities or parts of yourself do you have to hide to feel accepted and loved?", "people", false,"phillip", false,"",6],
["What do you need to hear right now to feel worthy and loved?", "identity", false,"phillip", false,"",6],
["Are there any negative qualities or patterns you have copied from someone out of loyalty or a desire to be accepted by them? If you let that behavior go would it affect your relationship with them? What do you need to feel safe to release this behavior?", "people", false,"phillip", false,"",6],
["What benefits do you think you are getting from your negative behaviors?", "tendencies", false,"phillip", false,"",6],
["Have you ever projected your own insecurities or fear onto someone else? Where do you think that came from?", "tendencies", false,"phillip", false,"",6],
["Do you put your needs first, or do you always take care of other people and neglect yourself? What are you afraid will happen if you prioritize yourself first?", "people", false,"phillip", false,"",6],
["Are there any boundaries you let people cross time and time again? What could happen if you didn't compromise on your boundaries?", "people", false,"phillip", true,"",6],
["Do you feel safe disagreeing with people or expressing your opinions?", "people", false,"phillip", false,"",6],
["Do you link your value to your achievements? If you didn't achieve the things society says you should, do you still feel worthy of happiness?", "identity", false,"phillip", false,"",6],
["Is there anyone you often compare yourself to and end up falling short? Why are they your measure of your success, value, and worth?", "people", false,"phillip", false,"",6],
["Would it be safe to be happy as just the best version of you, flaws and all?", "identity", false,"phillip", false,"",6],
["When was a time you needed someone to support you and they didn't, how could you offer that support to yourself?", "people", false,"phillip", false,"",6],
["When have you given your power away by blaming someone else for your actions, reactions, or inactions?", "people", false,"phillip", false,"",6],
["Pretend no one else exists, how do you visualize your dream life? What are you not doing right now because you are afraid of how others will react?", "fantasy", false,"phillip", false,"",6],
["What times have you felt most ashamed of your life? What/who caused the shame?", "dislikes", false,"phillip", false,"",7],
["What unfulfilled dream scares you the most?", "goals", false,"phillip", false,"",6],
["What is your mother's worst trait? Do you share this trait?", "people", false,"phillip", true,"",7],
["What is your father's worst trait? Do you share this trait?", "people", false,"phillip", true,"",7],
["Do you allow yourself to be sad when unhappy life events arise?", "dislikes", false,"phillip", false,"",4],
["Have you experienced grief or loss in your life? Do you feel like you could have saved this person?", "experience", false,"phillip", true,"",7],
["Do you blame a parent or caregiver for anything? Can you make sense of their behavior?", "people", false,"phillip", true,"",7],
["What does self-love look like to you?", "identity", false,"phillip", false,"",4],
["Tell us about the last time you felt that someone truly understood you.", "people", false,"phillip", false,"",5],
["What's the nicest thing you've ever done?", "experience", false,"coderystal", true,"",4],
["Why are you single/not single?", "people", true,"coderystal", true,"",5],
["What's your rice purity score?", "experience", false,"coderystal", true,"",3],
["What do you think your rice purity score will be when you die?", "worldview", false,"coderystal", true,"",4],
["What's your favorite part about existing?", "worldview", false,"BrittanySimon", false,"",2],
["What's your favorite part about existence?", "worldview", false,"BrittanySimon", false,"",2],
["When is the earliest you would get married?", "worldview", false,"coderystal", true,"",2],
["What's something you want brutal advice about?", "tendencies", false,"strangers", true,"",5],
["What's a skill that you think every single person in the world should reasonably have?", "worldview", false,"coderystal", true,"",2],
["How often do you tell the truth when people ask how you are?", "people", false,"coderystal", true,"",4],
["How would you describe yourself?", "identity", false,"strangers", true,"",3],
["How do you think other people would describe you?", "identity", false,"strangers", true,"",3],
["What does it take to earn your vulnerability? Have I earned it?", "people", false,"strangers", true,"",4],
["What's the nicest or most significant compliment you've ever gotten?", "identity", false,"coderystal", true,"",4],
["What's the most surprising thing someone has told you about yourself?", "identity", false,"coderystal", true,"",3],
["When was the last time you tried something new?", "experience", false,"toastmasters", false,"",2],
["Who do you sometimes compare yourself to?", "goals", false,"toastmasters", false,"",4],
["What's the most sensible thing you've ever heard someone say?", "worldview", false,"toastmasters", false,"",2],
["What gets you excited about life?", "goals", false,"toastmasters", false,"",4],
["What life lesson did you learn the hard way?", "experience", false,"toastmasters", false,"",5],
["What do you wish you spent more time doing five years ago?", "fantasy", false,"toastmasters", false,"",4],
["Do you ask enough questions or do you settle for what you know?", "tendencies", false,"toastmasters", false,"",4],
["Who do you love and what are you doing about it?", "people", true,"toastmasters", false,"",6],
["What's a belief that you hold with which many people disagree?", "worldview", false,"toastmasters", false,"",4],
["What can you do today that you were not capable of a year ago?", "experience", false,"toastmasters", false,"",5],
["Do you think crying is a sign of weakness or strength?", "worldview", false,"toastmasters", false,"",3],
["What would you do differently if you knew nobody would judge you?", "fantasy", false,"toastmasters", false,"",4],
["Do you celebrate the things you do have?", "tendencies", false,"toastmasters", false,"",3],
["What is the difference between living and existing?", "worldview", false,"toastmasters", false,"",3],
["If not now, then when?", "goals", true,"toastmasters", false,"",4],
["Have you done anything lately worth remembering?", "experience", false,"toastmasters", false,"",4],
["What does your joy look like today?", "tendencies", false,"toastmasters", false,"",4],
["Is it possible to lie without saying a word?", "worldview", false,"toastmasters", false,"",2],
["If you had a friend who spoke to you in the same way that you sometimes speak to yourself, how long would you allow this person to be your friend?", "identity", false,"toastmasters", false,"",6],
["Which activities make you lose track of time?", "likes", false,"toastmasters", false,"",4],
["If you had to teach something, what would you teach?", "goals", false,"toastmasters", false,"",3],
["What would you regret not fully doing, being or having in your life?", "goals", false,"toastmasters", false,"",5],
["Are you holding onto something that you need to let go of?", "tendencies", false,"toastmasters", false,"",5],
["When you are 80-years-old, what will matter to you the most?", "goals", false,"toastmasters", false,"",4],
["When is it time to stop calculating risk and rewards and just do what you know is right?", "worldview", false,"toastmasters", false,"",4],
["How old would you be if you didn't know how old you are?", "identity", false,"toastmasters", false,"",3],
["Would you break the law to save a loved one?", "people", false,"toastmasters", false,"",2],
["What makes you smile?", "likes", false,"toastmasters", false,"",1],
["When it's all said and done, will you have said more than you've done?", "goals", false,"toastmasters", false,"",4],
["If you had the opportunity to get one message across to a large group of people, what would it be?", "worldview", false,"toastmasters", true,"",4],
["If the average human lifespan was 40 years, how would you live your life differently?", "fantasy", false,"toastmasters", false,"",4],
["If you could choose one book as a mandatory read for all high school students, which book would you choose?", "worldview", false,"toastmasters", false,"",4],
["Would you rather have less work or more work you actually enjoy doing?", "fantasy", false,"toastmasters", false,"",3],
["What is important enough to go to war over?", "worldview", false,"toastmasters", false,"",4],
["Which is worse, failing or never trying?", "tendencies", false,"toastmasters", false,"",2],
["When was the last time you listened to the sound of your own breathing?", "tendencies", false,"toastmasters", false,"",1],
["What's something you know you do differently than most people?", "identity", false,"toastmasters", false,"",4],
["How have you experienced the legacy of 'The American Dream'?", "worldview", false,"toastmasters", true,"",4],
["Would you rather be a worried genius or a joyful simpleton?", "fantasy", false,"toastmasters", false,"",2],
["If you could instill one piece of advice in a newborn baby's mind, what advice would you give?", "goals", false,"toastmasters", false,"",4],
["What is the most desirable trait another person can possess?", "people", false,"toastmasters", false,"",2],
["What's the most reprehensible thing that you would feel justified in doing?", "worldview", false,"toastmasters", true,"",4],
["What do you want most?", "goals", false,"toastmasters", false,"",6],
["Are you more worried about doing things right, or doing the right things?", "tendencies", false,"toastmasters", false,"",4],
["What has life taught you recently?", "experience", false,"toastmasters", false,"",3],
["What is the one thing you would most like to change about the world?", "goals", false,"toastmasters", false,"",6],
["Where do you find inspiration?", "worldview", false,"toastmasters", false,"",3],
["What have you noticed?", "experience", true,"coderystal", true,"",4],
["How did you notice?", "tendencies", true,"coderystal", true,"",4],
["Can you describe your life in a six word sentence?", "identity", false,"toastmasters", false,"",3],
["Why are you afraid to make a mistake?", "worldview", false,"toastmasters", true,"",4],
["What impact do you want to leave on the world?", "goals", false,"phillip, toastmasters", false,"",6],
["What is the most defining moment of your life thus far?", "experience", false,"toastmasters", false,"",6],
["In the haste of your daily life, what are you not seeing?", "tendencies", false,"toastmasters", false,"",3],
["Why do you not do what you want to do, and do what you hate?", "worldview", false,"toastmasters", true,"",4],
["What lifts your spirits when life gets you down?", "likes", false,"toastmasters", false,"",4],
["Have you ever regretted something you did not say or do?", "experience", false,"toastmasters", false,"",5],
["Has your greatest fear ever come true?", "experience", false,"toastmasters", false,"",6],
["Who do you think about recently that you haven't seen in a while?", "people", false,"toastmasters", true,"",4],
["What is your most beloved childhood memory? What makes it so special?", "people", false,"toastmasters", true,"",4],
["Is it more important to love or be loved?", "worldview", false,"toastmasters", false,"",2],
["If it all came back around to you, would it help you or hurt you?", "worldview", false,"toastmasters", false,"",4],
["If you had the chance to go back in time and change one thing would you do it?", "fantasy", false,"toastmasters", false,"",4],
["If a doctor gave you five years to live, what would you try to accomplish?", "goals", false,"toastmasters", false,"",4],
["What is the difference between falling in love and being in love?", "worldview", false,"toastmasters", false,"",2],
["Who do you think stands between you and happiness?", "people", false,"toastmasters", false,"",6],
["What is the difference between innocence and ignorance?", "worldview", false,"toastmasters", false,"",2],
["What is the simplest truth you can express in words?", "worldview", false,"toastmasters", false,"",4],
["What gives your life meaning?", "identity", false,"toastmasters", false,"",6],
["Can there be happiness without sadness? Pleasure without pain? Peace without war?", "worldview", false,"toastmasters", false,"",2],
["What's the one thing you'd like others to remember about you at the end of your life?", "identity", false,"toastmasters", false,"",4],
["Is there such a thing as perfect?", "worldview", true,"toastmasters", false,"",2],
["To what degree have you actually controlled the course your life has taken?", "worldview", false,"toastmasters", false,"",4],
["What does it mean to be human?", "worldview", true,"toastmasters", true,"",6],
["What's the most fundamental difference between you and your enemy?", "worldview", false,"toastmasters", true,"",6],
["What do you love most about yourself?", "identity", false,"toastmasters", false,"",6],
["Where would you most like to go?", "goals", false,"toastmasters", false,"",2],
["Is it more important to do what you love or to love what you are doing?", "goals", false,"toastmasters", false,"",2],
["What do you imagine yourself doing ten years from now?", "goals", false,"toastmasters", false,"",3],
["What small act of kindness were you once shown that you will never forget?", "people", false,"toastmasters", false,"",5],
["Do you own your things or do your things own you?", "tendencies", false,"toastmasters", false,"",5],
["Would you rather lose all of your old memories or never be able to make new ones?", "fantasy", false,"toastmasters", false,"",2],
["How do you deal with someone in a position of power who wants you to fail?", "experience", false,"toastmasters", false,"",6],
["What do you have that you cannot live without?", "identity", false,"toastmasters", false,"",2],
["When you close your eyes what do you see?", "tendencies", false,"toastmasters", false,"",1],
["What sustains you on a daily basis?", "experience", false,"toastmasters", false,"",2],
["What are your top five personal values?", "identity", false,"toastmasters", false,"",6],
["Why can't you remember?", "experience", true,"coderystal", true,"",5],
["Why must you love someone enough to let them go?", "people", false,"toastmasters", false,"",2],
["Do you ever celebrate the green lights?", "tendencies", false,"toastmasters", false,"",3],
["How are your fears imprisoning you?", "experience", false,"toastmasters", true,"",7],
["What one thing have you not done that you really want to do?", "goals", false,"toastmasters", false,"",3],
["Why are you, you?", "identity", false,"toastmasters", false,"",3],
["If you haven't achieved it yet what do you have to lose?", "tendencies", false,"toastmasters", false,"",4],
["What three words would you use to describe the last three months of your life?", "identity", false,"toastmasters", false,"",3],
["Is it ever right to do the wrong thing? Is it ever wrong to do the right thing?", "worldview", false,"toastmasters", false,"",2],
["How would you describe 'freedom' in your own words?", "worldview", false,"toastmasters", false,"",4],
["What is the most important thing you could do right now in your personal life?", "goals", false,"toastmasters", false,"",6],
["If you could ask one person, alive or dead, only one question, who would you ask and what would you ask?", "people", false,"toastmasters", false,"",4],
["If happiness was the national currency, what kind of work would make you rich?", "fantasy", false,"toastmasters", false,"",2],
["What is your number one goal for the next six months?", "goals", false,"toastmasters", false,"",4],
["Would you ever give up your life to save someone else?", "people", false,"toastmasters", false,"",6],
["Are you happy with yourself?", "identity", false,"phillip, toastmasters", false,"",6],
["What is the meaning of 'peace' to you?", "worldview", false,"toastmasters", false,"",4],
["What are three moral rules you will never break?", "worldview", false,"toastmasters", false,"",4],
["What does it mean to allow another person to truly love you?", "people", false,"toastmasters", false,"",6],
["Who or what do you think of when you think of love?", "people", false,"toastmasters", false,"",4],
["If your life was a novel, what would be the title and how would your story end?", "fantasy", false,"toastmasters", false,"",3],
["What would you not give up for $1,000,000 in cash?", "identity", false,"toastmasters", false,"",6],
["When do you feel most like yourself?", "identity", false,"toastmasters", false,"",6],
["When you help someone do you ever think, 'What's in it for me?'", "tendencies", false,"toastmasters", true,"",4],
["What is your greatest challenge?", "goals", false,"toastmasters", true,"",4],
["How do you know when it's time to continue holding on or time to let go?", "experience", false,"toastmasters", false,"",5],
["How do you define success?", "worldview", false,"toastmasters", false,"",4],
["If someone could tell you the exact day and time you are going to die, would you want them to tell you?", "worldview", false,"toastmasters", false,"",2],
["If I could grant you one wish what would you wish for?", "fantasy", false,"toastmasters", false,"",4],
["What have you read online recently that inspired you?", "experience", false,"toastmasters", false,"",4],
["How do you think religion both resonates and challenges (for you, and in general)? How are those forces related?", "worldview", false,"toastmasters", true,"",4],
["If you could live one day of your life over again, what day would you choose?", "fantasy", false,"toastmasters", false,"",4],
["What can money not buy?", "worldview", false,"toastmasters", false,"",2],
["What do you think would happen if you were to go off the grid and totally disappear tomorrow?", "identity", false,"toastmasters", true,"",4],
["Beyond the titles that others have given you, who are you?", "identity", false,"toastmasters", false,"",6],
["If you could live the next 24 hours and then erase it and start over just once, what would you do?", "fantasy", false,"toastmasters", false,"",2],
["Is it possible to know the truth without challenging it first?", "worldview", false,"toastmasters", false,"",2],
["What word best describes the way you've spent the last month of your life?", "identity", false,"toastmasters", false,"",3],
["What makes everyone smile?", "tendencies", false,"toastmasters", false,"",1],
["What do you owe yourself?", "identity", false,"toastmasters", false,"",6],
["What's a priceless experience you've had?", "experience", false,"toastmasters", true,"",2],
["Can you think of a time when the impossible became possible?", "experience", false,"toastmasters", true,"",5],
["How have you changed in the last five years?", "experience", false,"toastmasters", false,"",5],
["What are you sure of in your life?", "identity", false,"toastmasters", false,"",4],
["When you think of 'home,' what, specifically, do you think of?", "people", false,"toastmasters", false,"",3],
["What's the difference between settling for things and accepting the way things are?", "worldview", false,"toastmasters", false,"",2],
["How many of your friends would you trust with your life?", "people", false,"toastmasters", false,"",4],
["What's your definition of heaven?", "fantasy", false,"toastmasters", false,"",4],
["What is your most prized possession?", "identity", false,"toastmasters", false,"",3],
["How would you describe yourself in one sentence?", "identity", false,"toastmasters", false,"",3],
["How do you know you're alive?", "identity", true,"coderystal", true,"",6],
["What stands between you and happiness?", "goals", false,"phillip, toastmasters", true,"",6],
["What makes a person beautiful?", "people", false,"toastmasters", false,"",4],
["Is there ever a time when giving up makes sense?", "experience", false,"toastmasters", false,"",4],
["What makes you proud?", "tendencies", false,"toastmasters", false,"",4],
["How do you find the strength to do what you know in your heart is right?", "experience", false,"toastmasters", false,"",6],
["Where do you find peace?", "worldview", false,"toastmasters", false,"",2],
["When have you worked hard and loved every minute of it?", "experience", false,"toastmasters", false,"",4],
["How short would your life have to be before you would start living differently today?", "worldview", false,"toastmasters", false,"",4],
["Is it better to have loved and lost or to have never loved at all?", "people", false,"toastmasters", false,"",2],
["What would you do if you made a mistake and somebody died?", "worldview", false,"toastmasters", false,"",3],
["Who do you trust?", "people", false,"toastmasters", false,"",5],
["If you were forced to eliminate every physical possession from your life with the exception of what could fit into a single backpack, what would you put in it?", "likes", false,"toastmasters", false,"",2],
["When does silence convey more meaning than words?", "worldview", false,"toastmasters", false,"",4],
["How do you spend the majority of your free time?", "tendencies", false,"toastmasters", false,"",3],
["Who do you think of first when you think of 'success?'", "people", false,"toastmasters", false,"",4],
["What did you think you would be when you grew up?", "fantasy", false,"toastmasters", true,"",3],
["How will today matter in five years from now?", "worldview", false,"toastmasters", false,"",4],
["How have you helped someone else recently?", "experience", false,"toastmasters", false,"",3],
["What is your greatest skill?", "identity", false,"toastmasters", false,"",3],
["Do you see to believe or believe to see?", "worldview", false,"toastmasters", false,"",4],
["How are you pursuing your dreams right now?", "goals", false,"toastmasters", false,"",3],
["What's the next big step you need to take?", "goals", false,"toastmasters", false,"",5],
["If today was the last day of your life, would you want to do what you are about to do today?", "tendencies", false,"toastmasters", false,"",3],
["If today was the last day of your life, who would you call and what would you tell them?", "people", false,"toastmasters", false,"",6],
["Who do you dream about?", "people", false,"toastmasters", false,"",4],
["What do you have trouble seeing clearly in your mind?", "experience", false,"toastmasters", false,"",4],
["What are you looking forward to?", "goals", false,"toastmasters", false,"",3],
["When is love a weakness?", "people", false,"toastmasters", false,"",2],
["What has been the most terrifying moment of your life thus far?", "experience", false,"toastmasters", false,"",5],
["Who is the strongest person you know?", "people", false,"toastmasters", false,"",4],
["If you could take a single photograph of your life, what would it look like?", "fantasy", false,"toastmasters", false,"",3],
["Is the reward worth the risk?", "worldview", true,"toastmasters", false,"",4],
["For you personally, what makes today worth living?", "worldview", false,"toastmasters", false,"",4],
["What have you done in the last year that makes you proud?", "experience", false,"toastmasters", false,"",6],
["What did you learn recently that changed the way you live?", "worldview", false,"toastmasters", false,"",5],
["What is your fondest memory from the past three years?", "experience", false,"toastmasters", false,"",4],
["What are the primary components of a happy life?", "worldview", false,"toastmasters", false,"",4],
["How would the world be different if you were never born?", "identity", false,"toastmasters", false,"",6],
["What is your favorite song?", "identity", false,"toastmasters", false,"",2],
["With the resources you have right now, what can you do to bring yourself closer to your goal?", "goals", false,"toastmasters", false,"",4],
["What are your top three priorities?", "goals", false,"toastmasters", false,"",6],
["What do you think about celebrity culture?", "worldview", false,"toastmasters", true,"",2],
["What is the nicest thing someone has ever done for you?", "experience", false,"toastmasters", false,"",4],
["What do you see when you look into the future?", "worldview", false,"toastmasters", false,"",3],
["What makes you angry or defensive?", "tendencies", false,"phillip, toastmasters", true,"",6],
["What is the most valuable life lesson you learned from your parents?", "experience", false,"toastmasters", false,"",5],
["What does love feel like?", "people", false,"toastmasters", false,"",2],
["What are your favorite simple pleasures?", "tendencies", false,"toastmasters", false,"",2],
["If you could go back in time and tell a younger version of yourself one thing, what would you tell?", "experience", false,"toastmasters", false,"",5],
["What do you do to deliberately impress others?", "tendencies", false,"toastmasters", false,"",3],
["What will you never do?", "tendencies", false,"toastmasters", false,"",4],
["Excluding romantic relationships, who do you love?", "people", false,"toastmasters", false,"",4],
["What is your earliest childhood memory?", "experience", false,"toastmasters", false,"",3],
["What book has had the greatest influence on your life?", "experience", false,"toastmasters", false,"",3],
["What three questions do you wish you knew the answers to?", "fantasy", false,"toastmasters", false,"",4],
["What is the greatest peer pressure you've ever felt?", "experience", false,"toastmasters", false,"",4],
["What's the biggest lie you once believed was true?", "worldview", false,"toastmasters", false,"",5],
["In your lifetime, what have you done that hurt someone else?", "experience", false,"toastmasters", false,"",5],
["What's the best part of growing older?", "experience", false,"toastmasters", false,"",2],
["What's been on your mind most lately?", "worldview", false,"toastmasters", false,"",3],
["What do you think is worth waiting for?", "worldview", false,"toastmasters", false,"",4],
["What chances do you wish you had taken?", "goals", false,"toastmasters", false,"",4],
["Where else would you like to live?", "likes", false,"toastmasters", false,"",2],
["What motivates you to go to work each day?", "tendencies", false,"toastmasters", false,"",4],
["What do you wish you had done differently?", "experience", false,"toastmasters", false,"",5],
["What is your greatest strength and your greatest weakness?", "identity", false,"toastmasters", false,"",5],
["When was the last time you lied? What did you lie about?", "experience", false,"toastmasters", false,"",4],
["What made you smile this week?", "experience", false,"toastmasters", false,"",2],
["What do you do with the majority of your money?", "tendencies", false,"toastmasters", false,"",3],
["What motivates you to be your best?", "tendencies", false,"toastmasters", false,"",4],
["When was the last time you lost your temper? About what?", "tendencies", false,"toastmasters", false,"",6],
["What will you never give up on?", "identity", false,"toastmasters", false,"",6],
["When you look into the past, what do you miss the most?", "experience", false,"toastmasters", false,"",5],
["How would you describe the past year of your life in one sentence?", "identity", false,"toastmasters", false,"",3],
["What is the most spontaneous thing you've ever done?", "experience", false,"toastmasters", false,"",3],
["What makes you uncomfortable?", "tendencies", false,"toastmasters", false,"",4],
["If you had to move 3000 miles away, what one thing would you miss the most?", "people", false,"toastmasters", false,"",4],
["What worries you about the future?", "worldview", false,"toastmasters", false,"",4],
["What one 'need' and one 'want' will you strive to achieve in the next twelve months?", "goals", false,"toastmasters", false,"",4],
["What life lessons did you have to experience firsthand before you fully understood them?", "experience", false,"toastmasters", false,"",5],
["Do you like the city or town you live in?", "identity", false,"toastmasters", false,"",2],
["What's the best part of being you?", "identity", false,"toastmasters", false,"",3],
["When you look back over the past month, what single moment stands out?", "experience", false,"toastmasters", false,"",4],
["What do you do to relieve stress?", "tendencies", false,"toastmasters", false,"",3],
["What is your happiest memory?", "experience", false,"toastmasters", false,"",6],
["What is your saddest memory?", "experience", false,"toastmasters", false,"",6],
["What would you like to change?", "goals", false,"toastmasters", false,"",4],
["How many people do you love?", "people", false,"toastmasters", false,"",4],
["What's the best decision you've ever made?", "experience", false,"toastmasters", false,"",6],
["What's your favorite true story that you enjoy sharing with others?", "experience", false,"toastmasters", false,"",3],
["Right now, at this moment, what do you want most?", "goals", false,"toastmasters", false,"",6],
["What are you waiting for? How are you writing your life's story?", "goals", false,"toastmasters", false,"",4],
["What makes love last?", "people", false,"toastmasters", false,"",6],
["What good comes from suffering?", "worldview", false,"toastmasters", false,"",4],
["What's the most important lesson you've learned in the last year?", "experience", false,"toastmasters", false,"",5],
["Based on you current daily actions and routines, where would you expect to be in five years?", "goals", false,"phillip, toastmasters", true,"",3],
["What was your last major accomplishment?", "experience", false,"toastmasters", false,"",4],
["Through all of life's twists and turns who has been there for you?", "people", false,"toastmasters", false,"",5],
["What or who has been distracting you?", "people", false,"toastmasters", false,"",4],
["What are you looking forward to in the upcoming week?", "goals", false,"toastmasters", false,"",3],
["Who is your mentor and what have you learned from them?", "people", false,"toastmasters", false,"",5],
["What are you uncertain about?", "worldview", false,"toastmasters", false,"",3],
["What do you think about when you lie awake in bed?", "worldview", false,"toastmasters", false,"",3],
["What's something most people don't know about you?", "identity", false,"toastmasters", false,"",3],
["When you have a random hour of free time, what do you usually do?", "tendencies", false,"toastmasters", false,"",3],
["What makes you weird?", "identity", false,"toastmasters", false,"",3],
["If you could relive yesterday what would you do differently?", "experience", false,"toastmasters", false,"",4],
["What do you do over and over again that you hate doing?", "tendencies", true,"toastmasters", false,"",4],
["What would choose for your child on a zero-sum scale of intelligence to attractiveness?", "worldview", false,"toastmasters", true,"",2],
["What white lies do you often tell?", "tendencies", false,"toastmasters", false,"",3],
["What is the biggest change you have made in your life in the last year?", "experience", false,"toastmasters", false,"",5],
["What do you understand today about your life that you did not understand a year ago?", "experience", false,"toastmasters", false,"",5],
["Whose life have you had the greatest impact on?", "people", false,"toastmasters", false,"",5],
["What did life teach you yesterday?", "experience", false,"toastmasters", false,"",5],
["Who impresses you?", "people", false,"toastmasters", false,"",2],
["Why aren't you proud?", "experience", true,"phillip, toastmasters", true,"",6],
["When should you reveal a secret that you promised you wouldn't reveal?", "worldview", false,"toastmasters", false,"",3],
["What is the one primary quality you look for in a significant other?", "people", false,"toastmasters", false,"",2],
["What do you admire most about your mother and father?", "people", false,"toastmasters", false,"",4],
["What is the best advice you have ever received?", "experience", false,"toastmasters", false,"",4],
["If you could live forever, would you want to?", "fantasy", false,"toastmasters", false,"",2],
["If you had to be someone else for one day, who would you be?", "fantasy", false,"toastmasters", false,"",2],
["What positive changes have you made in your life recently?", "experience", false,"toastmasters", false,"",5],
["Who makes you feel good about yourself?", "people", false,"toastmasters", false,"",4],
["What is your biggest regret?", "experience", false,"phillip, toastmasters", false,"",5],
["Why is that okay?", "worldview", true,"coderystal", true,"",7],
["Which one of your responsibilities do you wish you could get rid of?", "experience", false,"toastmasters", false,"",2],
["What's something you don't like to do that you are still really good at?", "dislikes", false,"toastmasters", false,"",3],
["Who would know?", "people", true,"coderystal", true,"",4],
["What type of person angers you the most?", "dislikes", false,"toastmasters", false,"",6],
["What is missing in your life?", "goals", true,"toastmasters", false,"",6],
["What is your most striking physical attribute?", "identity", false,"toastmasters", false,"",3],
["What has fear of failure stopped you from doing?", "tendencies", false,"toastmasters", false,"",4],
["Who would you like to please the most?", "people", false,"toastmasters", false,"",4],
["If you could go back in time and change things, what would you change about the week that just passed?", "experience", false,"toastmasters", false,"",4],
["When you meet someone for the very first time, what do you want them to think about you?", "identity", false,"toastmasters", false,"",4],
["Who would you like to forgive?", "people", false,"toastmasters", false,"",4],
["At what point during the last five years have you felt lost and alone?", "experience", false,"toastmasters", false,"",7],
["What is one opportunity you believe you missed out on when you were younger?", "fantasy", false,"toastmasters", false,"",4],
["What do you want more of in your life?", "goals", false,"toastmasters", false,"",4],
["What do you want less of in your life?", "goals", false,"toastmasters", false,"",4],
["Who depends on you?", "people", false,"toastmasters", false,"",6],
["Who has had the greatest impact on your life?", "people", false,"toastmasters", false,"",5],
["Are you happy with where you are in your life?", "identity", false,"toastmasters", false,"",6],
["In one year from today, how do you think your life will be different?", "goals", false,"toastmasters", false,"",4],
["How have you sabotaged yourself in the past five years?", "tendencies", false,"toastmasters", false,"",6],
["Other than money, what else have you gained from your current job?", "experience", false,"toastmasters", false,"",3],
["Whom do you secretly envy?", "worldview", false,"toastmasters", false,"",4],
["In twenty years, what do you want to remember?", "goals", false,"toastmasters", false,"",4],
["What are you most excited about for your life?", "likes", false,"toastmasters", true,"",3],
["What are you most excited about for today?", "likes", false,"toastmasters", true,"",3],
["What experience from this past year do you appreciate the most?", "experience", false,"toastmasters", false,"",4],
["What is the most enjoyable thing your family has done together in the last three years?", "experience", false,"toastmasters", false,"",4],
["How many hours of television do you watch in a week? A month? A year?", "tendencies", false,"toastmasters", false,"",3],
["What is the biggest obstacle that stands in your way right now?", "goals", false,"toastmasters", false,"",5],
["What do you sometimes pretend you understand that you really don't?", "tendencies", false,"toastmasters", false,"",3],
["What do you like most about your job? What do you dislike most about your job?", "experience", false,"toastmasters", false,"",4],
["What's something new you recently learned about yourself?", "identity", false,"toastmasters", false,"",5],
["In one sentence, how would you describe your relationship with your mother?", "people", false,"toastmasters", false,"",6],
["What was the most defining moment in your life during this past year?", "experience", false,"toastmasters", false,"",5],
["What's the number one change you need to make in your life in the next twelve months?", "goals", false,"toastmasters", false,"",5],
["What makes you feel secure?", "identity", false,"toastmasters", false,"",6],
["What is your favorite sound?", "likes", false,"toastmasters", false,"",2],
["What are the top three qualities you look for in a friend?", "people", false,"toastmasters", false,"",4],
["What simple gesture have you recently witnessed that renewed your hope in humanity?", "worldview", false,"toastmasters", false,"",2],
["What is your favorite smell?", "likes", false,"toastmasters", false,"",2],
["What recent memory makes you smile the most?", "experience", false,"toastmasters", false,"",4],
["In one word, how would you describe your childhood?", "identity", false,"toastmasters", false,"",3],
["What celebrities do you admire?", "people", false,"toastmasters", false,"",2],
["What is the number one motivator in your life right now?", "goals", false,"toastmasters", false,"",5],
["What music do you listen to to lift your spirits when you're feeling down?", "likes", false,"toastmasters", false,"",4],
["If I gave you $1000 and told you that you had to spend it today, what would you buy?", "fantasy", false,"toastmasters", false,"",3],
["What was the last thing that made you laugh out loud?", "experience", false,"toastmasters", false,"",3],
["What is your biggest pet peeve?", "dislikes", false,"toastmasters", false,"",2],
["Who was the last person you said 'I love you' to?", "people", false,"toastmasters", false,"",5],
["What is your biggest phobia?", "identity", false,"toastmasters", false,"",3],
["What are some recent compliments you've received?", "people", false,"toastmasters", false,"",4],
["How many friends do you have in real life that you talk to regularly?", "people", false,"toastmasters", false,"",3],
["How much money per month is enough for you to live comfortably?", "goals", false,"toastmasters", false,"",3],
["When was your first impression of someone totally wrong?", "experience", false,"toastmasters", false,"",3],
["How many hours a week do you spend online?", "tendencies", false,"toastmasters", false,"",3],
["What do you love to do?", "likes", false,"toastmasters", false,"",6],
["What specific character trait do you want to be known for?", "identity", false,"toastmasters", false,"",4],
["Are you more like your mom or your dad? In what way?", "people", false,"toastmasters", false,"",5],
["What is the number one quality that makes someone a good leader?", "people", false,"toastmasters", false,"",2],
["What bad habits do you want to break?", "tendencies", false,"toastmasters", false,"",5],
["What is your favorite place on Earth?", "likes", false,"toastmasters", false,"",2],
["What do you love to practice?", "tendencies", false,"toastmasters", false,"",3],
["What questions do you often ask yourself?", "tendencies", false,"toastmasters", false,"",4],
["What are you an expert at?", "identity", false,"toastmasters", false,"",4],
["How would an extra $1000 a month change your life?", "fantasy", false,"toastmasters", false,"",3],
["What things in life should always be free?", "worldview", false,"toastmasters", false,"",2],
["What is your favorite time of the year?", "likes", false,"toastmasters", false,"",1],
["What is something you have always wanted since you were a kid?", "fantasy", false,"toastmasters", false,"",4],
["What is the most recent dream you remember having while sleeping?", "fantasy", false,"toastmasters", false,"",3],
["What confuses you?", "tendencies", false,"toastmasters", false,"",4],
["What is your favorite quote?", "likes", false,"toastmasters", false,"",2],
["What is your favorite fictional story? (novel, movie, fairytale, etc.)", "likes", false,"toastmasters", false,"",2],
["Where or who do you turn to when you need good advice?", "people", false,"toastmasters", false,"",3],
["What artistic medium do you use to express yourself?", "tendencies", false,"toastmasters", false,"",3],
["Who or what is the greatest enemy of mankind?", "worldview", false,"toastmasters", false,"",6],
["What's something you wish you had done earlier in life?", "fantasy", false,"toastmasters", false,"",4],
["What is the closest you have ever come to fearing for your life?", "experience", false,"toastmasters", false,"",7],
["How do you deal with isolation and loneliness?", "tendencies", false,"toastmasters", false,"",6],
["What do you know well enough to teach to others?", "identity", false,"toastmasters", false,"",4],
["What's a quick decision you once made that changed your life?", "experience", false,"toastmasters", false,"",5],
["What have you lost interest in recently?", "tendencies", false,"toastmasters", false,"",2],
["What makes life easier?", "worldview", false,"toastmasters", false,"",4],
["Why didn't you do it?", "identity", true,"coderystal", true,"",4],
["What was the last thing you furiously argued about with someone?", "experience", false,"toastmasters", false,"",6],
["What job would you never do no matter how much it paid?", "dislikes", false,"toastmasters", false,"",2],
["What is the number one solution to healing the world?", "worldview", false,"toastmasters", false,"",4],
["What could society do without?", "worldview", false,"toastmasters", false,"",2],
["What stresses you out?", "tendencies", false,"toastmasters", false,"",3],
["Now that it's behind you, what did you do last week that was memorable?", "experience", false,"toastmasters", false,"",2],
["Where do you spend most of your time while you're awake?", "tendencies", false,"toastmasters", false,"",3],
["What makes someone a hero?", "worldview", false,"toastmasters", false,"",1],
["When in your life have you been a victim of stereotyping?", "experience", false,"toastmasters", false,"",5],
["When was the last time you felt lucky?", "experience", false,"toastmasters", false,"",3],
["When did you first realize that life is short?", "worldview", false,"toastmasters", false,"",5],
["What is the most insensitive thing a person can do?", "dislikes", false,"toastmasters", false,"",4],
["What can someone do to grab your attention?", "tendencies", false,"toastmasters", false,"",3],
["What do you usually think about on your drive home from work?", "tendencies", false,"toastmasters", false,"",3],
["What's one downside of the modern day world?", "worldview", false,"toastmasters", false,"",2],
["What simple fact do you wish more people understood?", "worldview", false,"toastmasters", false,"",4],
["If you could do it all over again, would you change anything?", "fantasy", false,"toastmasters", false,"",5],
["How would you describe your future in three words?", "goals", false,"toastmasters", false,"",3],
["What made you realize that you're not invincible?", "experience", false,"coderystal", true,"",5],
["What do you crave?", "tendencies", true,"coderystal", true,"",6],
["How are you coping?", "tendencies", false,"coderystal", true,"",6],
["Are you a coward?", "tendencies", false,"coderystal", true,"",6],
["Who takes care of you?", "people", false,"coderystal", true,"",6],
["What's something consequential you've done?", "experience", false,"coderystal", true,"",3],
["What would you say to someone truly, deeply evil?", "worldview", false,"coderystal", true,"reflections on squid game season 3",4],
["What is one thing you want to change about yourself?", "dislikes", false,"coderystal", true,"",6],
["Did you make any new year's resolutions this year? How are they going?", "goals", false,"coderystal", true,"",4],
["What would it take?", "fantasy", true,"coderystal", true,"",5],
["What mistakes do you make over and over again?", "tendencies", false,"phillip", false,"",6],
["What did you want to be when you grew up?", "fantasy", false,"toastmasters", false,"",3],
["What are you 100% sure of right now?", "worldview", false,"hannah", false,"",4],
["How do you know what you want?", "goals", false,"coderystal", false,"",4],
["When was the last time you were happy about a red light?", "experience", false,"coderystal", true,"",1],
["Who do you think you are?", "identity", false,"coderystal", true,"",6],
["What gives you the right?", "identity", false,"coderystal", true,"",6],
["What's one way you can treat yourself today? Would you do it?", "likes", false,"coderystal", false,"Treat yo self - Tom and Donna",4],
["What's the difference between loving someone, and loving who you are to each other?", "people", false,"SarahLee", true,"Do you love me, or do you love us?",6],
["What's something you once really wanted, that you've since outgrown?", "identity", false,"coderystal", false,"",3],
["How much do you trust those who protect you?", "people", false,"jon.quadrillionaire", true,"20250809 reel - The house plant doesn't need to worry about weeds taking its water, but it does need someone to water it",7],
["When was the last time you screamed?", "experience", false,"flamingo", true,"",3],
["If someone you loved lost their memory, what's the first thing you would tell them about your relationship?", "people", false,"flamingo", true,"",6],
["What's something crazy you've purchased?", "likes", false,"flamingo", true,"",3],
["How many people from your past would be able to recognize you by your character today?", "identity", false,"flamingo", true,"What's the biggest way I've changed since we met?",6],
["How many of your friends would you say are categorically different from you?", "people", false,"coderystal", true,"Think of a scatterplot, or distribution graph.",6],
["What would be a simple way to make life too easy?", "worldview", false,"coderystal", true,"",1],
["When was the last time you appreciated someone's unique perspective?", "people", false,"coderystal", true,"",4],
["What do you deserve?", "identity", true,"coderystal", true,"",7],
["What do you want to forget?", "worldview", false,"insidethenout", false,"prompt from guided journal ad",7],
["Have you forgiven yourself?", "identity", true,"insidethenout", false,"prompt from guided journal ad",6],
["Are you settling?", "worldview", true,"insidethenout", true,"prompt from guided journal ad, 'Are you settling for less than you are worth?'",6],
["What are you running from at the moment?", "tendencies", false,"insidethenout", false,"prompt from guided journal ad",6],
["Who hurt you?", "experience", false,"coderystal", true,"",7],
["Would you go?", "worldview", true,"coderystal", true,"eg, if you were invited (to that event, that wedding - knowing what you know or they know), or in general, how do you respond to opportunity?",3],
["When was the last time you were surprised?", "experience", false,"coderystal", true,"",1],
["When was the last time you were brave?", "experience", false,"coderystal", true,"",3],
["What's the best case scenario?", "worldview", true,"coderystal", true,"",4],
["What's the worst case scneario?", "worldview", true,"coderystal", true,"",6],
["What more do you need?", "goals", true,"coderystal", true,"",4],
["What are you trying to avoid?", "tendencies", true,"coderystal", true,"",4],
["What kind of influence do you have?", "people", false,"coderystal", true,"",4],
["What are your responsibilities?", "identity", true,"coderystal", true,"",4],
["What do you wish were not true?", "dislikes", false,"coderystal", true,"",4],
["Is there anything keeping you from realizing how good you have it?", "worldview", false,"coderystal", true,"words of wisdom from Talia Turner, a friend, paraphrased, regarding something you miss - you might not ever find anything that's exactly the same, or replicate what you lost, but there will be other things that have the potential to be just as good, maybe better, in different ways. I just so wanted exactly what that was.",4],
["Will it ever be the same?", "experience", true,"coderystal", true,"Is there anything that's changed forever, that you want to talk about?",5],
["If someone started a sentence with 'between you and I', what would you be expecting?", "people", false,"HelloHayes", true,"alexandrahayesrobinson reel from 20251113, regarding the phrase 'between you and I'",3],
["How do you imagine the people closest to you talk about you when you're not around?", "people", false,"coderystal", true,"if played in a group, how do you imagine we talk ..., then let the group respond",4],
["How often do you mention people in your life in conversation?", "people", false,"coderystal", true,"There's someone I haven't met.",3],
["How do you feel about the idea of going to a concert by yourself?", "tendencies", false,"coderystal", true,"I went alone to Maisie Peters 202510, and to Henrik 202511. I made friends there! It was cool.",3],
["When was the last time you willingly did something at your own expense?", "experience", false,"coderystal", true,"ie out of responsibility, commitment, something greater",5],
["What do we owe to each other?", "worldview", false,"TheGoodPlace", false,"",4],
["What's something that's not your concern?", "worldview", false,"coderystal", true,"I have to tell someone, I'm not your problem.",3],
["When's the last time you were so confident that you made a careless mistake?", "experience", false,"coderystal", true,"kitchen mishap 20251113",3],
["Who are you no longer willing to be?", "identity", false,"insidethenout", false,"prompt from Dig Deeper guided journal ad",7],
["What drains your energy?", "tendencies", false,"insidethenout", false,"prompt from Dig Deeper guided journal ad",6],
["What is something you are tolerating that you do not want to be?", "dislikes", false,"insidethenout", false,"prompt from Dig Deeper guided journal ad",7],
["What do you love most about your life right now?", "likes", false,"insidethenout", false,"prompt from Dig Deeper guided journal ad",6],
["If you knew for sure that you would never be found out, would you?", "worldview", true,"EmmaStone", false,"Amazing Spider Man 2 2014 promo on Unscripted, Emma Stone's question - never ever ever, would you would you?",2],
["If you had everything you ever wanted in the palm of your hand, what would you do next?", "fantasy", false,"EmmaStone", true,"Amazing Spider Man 2 2014 promo on Unscripted, Emma Stone's question (she didn't finish her sentence)",2],
["Which of your birthdays was your favorite?", "experience", false,"phillip", false,"Phillip asked me on my birthday, leads to thoughts on birthdays generally",3],
["What's one of your good habits?", "tendencies", false,"coderystal", true,"brag and encourage",3],
["What would it take for you to try to stop a wedding?", "worldview", false,"coderystal", true,"Gilmore Girls season 4 episode 4 - what would you have done? also, if you had feelings for someone",3],
["If you could dispense 5 liquids from your fingers, infinitely, and for free, what would you choose?", "fantasy", false,"KatieWood", true,"katiewood____ reel 20251208 dispense 5 liquids from your fingertips",2],
["If you could survive forever but never be rescued, how long would you float around in space before you took your helmet off?", "fantasy", false,"KatieWood", false,"katiewood____ reel 20251208",2],
["If you could remove one minor inconvenience forever, what would it be?", "fantasy", false,"KatieWood", false,"katiewood____ reel 20251208",2],
["If you could take one body part out of your body, clean or repair it, then put it back, what would it be and what would you do to it?", "fantasy", false,"KatieWood", false,"katiewood____ reel 20251208",2],
["How do you feel about never seeing some of the most important people in your life ever again?", "worldview", false,"coderystal", true,"thoughts about the afterlife premises in The Good Place and Eternity",3],
["Are you sure?", "tendencies", true,"coderystal", true,"My hairdresser asked me this many times",6],
["Is this what you wanted?", "goals", true,"coderystal", true,"song: Everything You Wanted, by Henrik",6],
["What are some things you're saving up money for?", "goals", false,"coderystal", true,"",3],
["Why would you do that?", "tendencies", true,"coderystal", true,"",5],
["How did this happen?", "worldview", true,"coderystal", true,"",5],
["What now?", "worldview", true,"coderystal", true,"",6],
["What do you want?", "likes", true,"coderystal", true,"",6],
["How can you be reached?", "tendencies", false,"coderystal", true,"platform, or how generally someone can get your attention / stay in your life",3],
["How is that possible?", "worldview", true,"coderystal", true,"",4],
["How can it be?", "worldview", true,"coderystal", true,"",4],
["Do you think you are (or would be) a better parent or sibling?", "people", false,"EdenWen", true,"asked our mom at family dinner if she would rather have herself as a mom or a sister; can also consider other roles (eg friend, classmate, community member)",6],
["Do you think your life is more affected by your parents or siblings?", "people", false,"EdenWen", true,"asked us all at family dinner if we would rather have our parent as a sibling or our sibling as a parent (etc, various combinations); I wondered if it should be an obvious answer, but hesitated",7],
["Would you rather be able to run at 40 miles per hour, or fly at a jogging pace?", "fantasy", false,"EdenWen", false,"asked us all at family dinner; I think there's an easy answer; can add layers by setting further restrictions (eg only in 1 direction, or if not able to jog)",2],
["Who do you support?", "people", false,"coderystal", true,"eg family, friends, public figures (celebrities, politicians)",4]]

let cats = [...new Set(completequestions.map((val) => val[1]))].sort()

//invites an answer that is a(n) ...
let intensityDict = {
    1: "comment - simple pleasantry",
    2: "window - mild musing that hints at your life and perspective",
    3: "introduction - safe personal description",
    4: "factor - recurring or otherwise relevant context",
    5: "influence - experience that directly shaped you",
    6: "theme - foundational, impactful, or otherwise superlative thought or feeling",
    7: "burden - potentially traumatic trigger"
}

let worksCited = "error..."
let authorDict = {
    "coderystal": "written for Conversatiles by <b>Coderystal</b>, probably still inspired by something else",
    "phillip": "gathered by <b>Phillip</b> Hoang from conferences and personal use",
    "toastmasters": "provided by <b>Toastmasters</b> for Table Topics",
    "strangers": "crafted by We're Not Really <b>Strangers</b> for card games",
    "hannah": "directed at me by <b>Hannah</b> Hsu",
    "flamingo": "designed by Tipsy <b>Flamingo</b> LLC for couple convos",
    "EdenWen": "asked by Eden Wen, a passionate psychology relevant critical thinking leader communication team worker (coderystal's little sister)"
}
let unqSrcs = new Set()
function calcSources() {
    let srcsArr = completequestions.map(qust=>qust[3])
    let srcs = new Set(srcsArr)
    srcs.forEach((src) => {
        if (src.includes(",")) {
            src.split(",").forEach((dupSrc)=> {
                unqSrcs.add(dupSrc.trim())
            })
        } else {
            unqSrcs.add(src)
        }

    })
    let srcCts = new Array()

    unqSrcs.forEach((src) => {
        let ct = srcsArr.filter((ele) => ele == src).length
        let partialArr = srcsArr.filter(ele => (ele.includes(src) && ele != src)).map(ele => 1/ele.split(",").length)
        if (partialArr.length > 0)
            ct += (partialArr.reduce((acc, cur)=>acc+cur))
        srcCts.push(ct+" - "+(src in authorDict ? authorDict[src] : ("attributed to <b>" + src + "</b>")))
    })
    srcCts.sort((a, b) => {
        return parseInt(b.split("-")[0]) - parseInt(a.split("-")[0])
    })

    worksCited = srcCts.reduce((acc,cur)=>acc+"<br>"+cur,"")
}
calcSources()